### PR TITLE
Keep it simple, bulwa!

### PR DESCRIPTION
**Pull request by pamil**

### CODE REVIEW

**Comment by Zales0123** [comment]
What does this branch name stand for? You should be more specific in naming, even with branches 😕

**Comment by pamil** [comment]
@Zales0123 it stands for all our lives!

**Comment by pamil** [comment]
For our freedom!

**Comment by pamil** [comment]
And for being merged quickly as this breaks the Behat suite on Sylius :tada:

**Comment by Zales0123** [comment]
I'm always 👍  for freedom 🐫

**Pull request merged**
